### ISSUE TITLE
如何类似的实现jsonrpc2.0？

### ISSUE THREAD

**Issue by Jackarain** [Jackarain/tinyrpc#1]
要做到和目前类似的方式，即，
类似调用
call(request, reply, yield[ec]);
request和reply可以是一个c++数据类型的结构。
通过static_json在内部序列化成json字符串并发送，然后等待远程reply的json，并解析成reply的c++结构
最后返回协程，继续执行。
其中要解决的问题：
1。request/reply的对应，可以在内部使用id来完成。
2。当对方返回reply的数据，由于reply可能是不同类型的c++结构，需要实现一个模板类来存储对应类型，可以在any_handler中保存为模板类型参数，再cast回原来的类型，并反序列化到c++结构，然后调用handler。（没想好）
3。当接收到远程rpc调用（没想好）
关于request和reply之间的id对应查找关系（没想好）

**Comment by IronsDu** [comment]
可以用代码生成来做。
比如：https://github.com/IronsDu/gayrpc/blob/master/src/gayrpc/core/GayRpcClient.h#L148 
 结合 https://github.com/IronsDu/gayrpc/blob/master/examples/echo/pb/echo_service.gayrpc.h#L81 。

如果用协程的话，对于“request/reply的对应” 问题，可以用channel来做：
https://github.com/IronsDu/coco/blob/master/tests/TestRpcClient.cpp#L28

**Comment by Jackarain** [comment]
@IronsDu

大致看了你的这个项目，做的非常不错，不过好像也并没有实现jsonrpc2.0
另外你的项目和我的设计目标稍有不同，主要是以为几个方面
1。tinyrpc是设计为asio风格的rpc通信，这里体现在所有io对象都是与io_context关联并由io_context调度。
2。tinyrpc是设计为类似beast的layered，这里，你与我也有所不同。
3。你是通过代码生成的方式来指定rpc函数和一些其它东西，这里我是更希望通过使用者自己bind相应的rpc函数。

总之你的实现有很多可以借鉴的地方，上面如果我说的不对，或有更好的思想，欢迎交流。

**Comment by IronsDu** [comment]
嗯，定位不一样哈，第1点是说网络库使用asio么？我感觉不应该和网络耦合呢。你说的第3点的bind，我不知道怎么保证服务的强类型的。

不过支持 jsonrpc2.0 的话，我感觉不难，用类似支持HTTP的一个拦截器可以实现：
https://github.com/IronsDu/gayrpc/blob/master/src/gayrpc/protocol/HttpProtocol.h#L49 
也类似使用asio库的拦截器：
https://github.com/IronsDu/coco/blob/master/tests/CoroutineRpc.h#L88

**Comment by Jackarain** [comment]
@IronsDu 

第一点问题不大，因为asio将来是c++标准，到时稍做调整即可。
类型是由c++来保证的，比如：
rpc_stub_.rpc_bind<chat::ChatSendMessage, chat::ChatReplyMessage>(
			std::bind(&rpc_session::chat_request, this,
				std::placeholders::_1, std::placeholders::_2));
和
void chat_request(const chat::ChatSendMessage& req, chat::ChatReplyMessage& reply)
必须匹配，保证签名符合：
void(const Request&, Reply&)

上面rpc_bind的类型要求则会在编译检查，rpc_bind内部也有相应的类型检查：
		template<class Request, class Reply, class Handler>
		void rpc_bind(Handler&& handler)
		{
			TINYRPC_HANDLER_TYPE_CHECK(Handler, void(const Request&, Reply&));

TINYRPC_HANDLER_TYPE_CHECK
用于更友好的提示handler类型签名

**Comment by IronsDu** [comment]
我的意思是客户端发送ChatSendMessage的话，它怎么能确定返回的是 ChatReplyMessage 呢？如果写错了怎么办呢？

**Comment by Jackarain** [comment]
@IronsDu 

就好比这个
https://github.com/Jackarain/tinyrpc/blob/master/example/client/websocket_client.cpp#L73
它就是你说的客户端发送ChatSendMessage，而reply是确定类型ChatReplyMessage，如果不是或者说写错了，那么当远程返回ChatReplyMessage消息的时候，就会解析失败，错误信息体现在error_code中。
